from ..spa import SPA
from ..spa.actions import Actions
from .buffer import Buffer
from .compare import Compare
from .circularconvolution import CircularConvolution
from .dotproduct import DotProduct
from ..spa.cortical import Cortical
from ..spa.input import Input
from ..spa.memory import Memory
from ..spa.module import Module
from .product import Product
from ..spa.utils import similarity
from .unitea import UnitEA
from ..spa.vocab import Vocabulary
