from ..spa import SPA
from .buffer import Buffer
from .compare import Compare
from .circularconvolution import CircularConvolution
from .dotproduct import DotProduct
from ..spa.input import Input
from ..spa.memory import Memory
from ..spa.module import Module
from .product import Product
from .unitea import UnitEA
